export const siteContent = {
  en: {
    meta: {
      title: "Imad Ahmad | Portfolio",
    },
    language: {
      label: "Language",
      english: "English",
      german: "Deutsch",
    },
    nav: {
      home: "Home",
      about: "About",
      portfolio: "Portfolio",
      contact: "Contact",
      emailLabel: "Email",
    },
    home: {
      greeting: "Hello",
      introLead: "I am",
      role: "MERN/MERN-Stack Developer with 4 years experience.",
      name: "Imad",
    },
    about: {
      firstName: "Imad",
      lastName: "Ahmad",
      infoGroups: [
        [
          { label: "Nationality", value: "Pakistan" },
          { label: "Based in", value: "Thuringia, Germany" },
          { label: "Languages", value: "English, German" },
        ],
        [
          { label: "Country", value: "Germany" },
          { label: "Phone", value: "0155 63 801481" },
          { label: "Email", value: "imadahmad.ia0@gmail.com" },
          { label: "Availability", value: "Open to freelance and full-time roles" },
        ],
      ],
      skillsTitle: "My Skills",
      skills: [
        "React JS",
        "MongoDB",
        "Angular JS",
        "Tailwind CSS",
        "Node JS",
        "JWT Auth",
        "Express JS",
        "Postman",
      ],
      resumeTitle: "My Resume",
      timeline: [
        {
          type: "education",
          title: "Master Degree",
          period: "2025 - Present",
          place: "TU Ilmenau",
        },
        {
          type: "experience",
          title: "MERN Developer",
          period: "May 2024 - May 2025",
          place: "i-TechEra Solution",
        },
        {
          type: "experience",
          title: "Frontend Developer",
          period: "Aug 2023 - Mar 2024",
          place: "Nitrocode",
        },
        {
          type: "experience",
          title: "Internship",
          period: "Mar 2023 - Jun 2023",
          place: "Contour Software",
        },
        {
          type: "education",
          title: "Bachelor Degree",
          period: "2023",
          place: "COMSATS University",
        },
      ],
    },
    facts: [
      { value: "4", label: "years of", accent: "experience" },
      { value: "12", label: "completed", accent: "projects" },
      { value: "17", label: "happy", accent: "customers" },
      { value: "13", label: "awards", accent: "won" },
      { value: "32", label: "learned", accent: "frameworks" },
    ],
    portfolio: {
      title: "My Portfolio",
      labels: {
        type: "Type",
        project: "Project",
        duration: "Duration",
        techStack: "Tech Stack",
        framework: "Framework",
      },
      preview: "Preview",
      toBeDeployed: "To be deployed",
      items: [
        {
          title: "Brussel Lake Paragon",
          type: "Website",
          project: "Freelance",
          duration: "2 months",
          techLabel: "techStack",
          techValue: "React.js, Node.js, Express.js, MongoDB",
          href: "https://www.brussellakeparagon.com/",
          cta: "preview",
        },
        {
          title: "e-Testing Service",
          type: "Web Application",
          project: "Academic Project",
          duration: "2022 - 2023",
          techLabel: "techStack",
          techValue: "React.js, Node.js, MySQL",
          href: "#",
          cta: "toBeDeployed",
        },
        {
          title: "Travel Ink Media",
          type: "Portfolio Website",
          project: "i-TechEra Solution",
          duration: "1.5 months",
          techLabel: "framework",
          techValue: "Framer",
          href: "https://www.travelinkmedia.com/",
          cta: "preview",
        },
        {
          title: "Meadow Ridge",
          type: "Website",
          project: "Business Website",
          duration: "2 months",
          techLabel: "techStack",
          techValue: "React.js, Node.js, Express.js, MongoDB",
          href: "https://meadowridgeftworth.com/",
          cta: "preview",
        },
      ],
    },
    testimonials: [
      {
        quote:
          "Not my first project with Imad. Fast, responsive, skilled, and great in communication. The entire process is always smooth and friendly, and once again I received a great website.",
        person: "Gyles Buckles",
        job: "CEO / Brussel Lake Paragon",
      },
      {
        quote:
          "Working with Imad has been an excellent experience. He consistently delivers high-quality work, stays responsive throughout the project, and ensures everything runs smoothly from start to finish. Highly recommended.",
        person: "Philip",
        job: "Travel Ink Media / D.O.P Director",
      },
    ],
    contact: {
      title: "Get in touch",
      phoneLabel: "phone",
      phone: "+49 155 63801481",
      addressLabel: "address",
      address: "Thuringia, Germany",
      emailLabel: "email",
      email: "imadahmad.ia0@gmail.com",
      followLabel: "follow me",
    },
    clientsTitle: "My Clients",
    blog: {
      title: "Latest Posts",
      commentsSuffix: "comments",
      readMore: "Read more",
      posts: [
        {
          category: "design",
          title: "How To Publish Content That Ranks On Google",
          excerpt:
            "A practical checklist for structuring articles, improving readability, and publishing content with stronger search visibility.",
          date: "9 Apr 2022",
          comments: "17 comments",
        },
        {
          category: "development",
          title: "How Efficient Site Structure Can Boost SEO",
          excerpt:
            "Small architecture choices can improve crawlability, user flow, and the long-term performance of your website.",
          date: "21 Feb 2022",
          comments: "34 comments",
        },
        {
          category: "essentials",
          title: "Change Management for Customer Success",
          excerpt:
            "A better rollout plan helps customers adapt faster, reduces friction, and protects trust during product updates.",
          date: "1 Jan 2022",
          comments: "10 comments",
        },
      ],
      article: {
        backToHome: "Back to home",
        pageTitle: "My Blog",
        tags: "wordpress, business",
        comments: "17 comments",
        heading: "How To Publish Content That Ranks On Google",
        imageAlt: "Blog article cover",
        paragraphs: [
          "Strong content starts with intent. Before writing, define the exact question the page should answer, the audience it should help, and the action you want readers to take next.",
          "From there, build a clear outline with descriptive headings, concise paragraphs, and useful examples. This gives both readers and search engines a better understanding of the topic and keeps the page easy to scan.",
          "Once the article is published, refine it over time. Update weak sections, improve internal links, and watch how people actually engage with the page. Consistent iteration is often what moves a good article into a high-performing one.",
        ],
      },
    },
    footer: {
      copyrightName: "Imad Ahmad",
      madeWithLovePrefix: "Made with",
      madeWithLoveSuffix: "by Imad",
    },
  },
  de: {
    meta: {
      title: "Imad Ahmad | Portfolio",
    },
    language: {
      label: "Sprache",
      english: "English",
      german: "Deutsch",
    },
    nav: {
      home: "Start",
      about: "Profil",
      portfolio: "Portfolio",
      contact: "Kontakt",
      emailLabel: "E-Mail",
    },
    home: {
      greeting: "Hallo",
      introLead: "Ich bin",
      role: "MERN-Stack-Entwickler mit 4 Jahren Erfahrung.",
      name: "Imad",
    },
    about: {
      firstName: "Imad",
      lastName: "Ahmad",
      infoGroups: [
        [
          { label: "Nationalitat", value: "Pakistan" },
          { label: "Standort", value: "Thuringen, Deutschland" },
          { label: "Sprachen", value: "Englisch, Deutsch" },
        ],
        [
          { label: "Land", value: "Deutschland" },
          { label: "Telefon", value: "0155 63 801481" },
          { label: "E-Mail", value: "imadahmad.ia0@gmail.com" },
          { label: "Verfugbarkeit", value: "Offen fur Freelance- und Festanstellungen" },
        ],
      ],
      skillsTitle: "Skills",
      skills: [
        "React JS",
        "MongoDB",
        "Angular JS",
        "Tailwind CSS",
        "Node JS",
        "JWT Auth",
        "Express JS",
        "Postman",
      ],
      resumeTitle: "Werdegang",
      timeline: [
        {
          type: "education",
          title: "Masterstudium",
          period: "2025 - Heute",
          place: "TU Ilmenau",
        },
        {
          type: "experience",
          title: "MERN Developer",
          period: "Mai 2024 - Mai 2025",
          place: "i-TechEra Solution",
        },
        {
          type: "experience",
          title: "Frontend Developer",
          period: "Aug 2023 - Mar 2024",
          place: "Nitrocode",
        },
        {
          type: "experience",
          title: "Praktikum",
          period: "Mar 2023 - Jun 2023",
          place: "Contour Software",
        },
        {
          type: "education",
          title: "Bachelorstudium",
          period: "2023",
          place: "COMSATS University",
        },
      ],
    },
    facts: [
      { value: "4", label: "Jahre", accent: "Erfahrung" },
      { value: "12", label: "abgeschlossene", accent: "Projekte" },
      { value: "17", label: "zufriedene", accent: "Kunden" },
      { value: "13", label: "gewonnene", accent: "Auszeichnungen" },
      { value: "32", label: "erlernte", accent: "Frameworks" },
    ],
    portfolio: {
      title: "Projekte",
      labels: {
        type: "Typ",
        project: "Projekt",
        duration: "Dauer",
        techStack: "Tech-Stack",
        framework: "Framework",
      },
      preview: "Ansehen",
      toBeDeployed: "Wird noch veroffentlicht",
      items: [
        {
          title: "Brussel Lake Paragon",
          type: "Website",
          project: "Freelance",
          duration: "2 Monate",
          techLabel: "techStack",
          techValue: "React.js, Node.js, Express.js, MongoDB",
          href: "https://www.brussellakeparagon.com/",
          cta: "preview",
        },
        {
          title: "e-Testing Service",
          type: "Webanwendung",
          project: "Akademisches Projekt",
          duration: "2022 - 2023",
          techLabel: "techStack",
          techValue: "React.js, Node.js, MySQL",
          href: "#",
          cta: "toBeDeployed",
        },
        {
          title: "Travel Ink Media",
          type: "Portfolio-Website",
          project: "i-TechEra Solution",
          duration: "1,5 Monate",
          techLabel: "framework",
          techValue: "Framer",
          href: "https://www.travelinkmedia.com/",
          cta: "preview",
        },
        {
          title: "Meadow Ridge",
          type: "Website",
          project: "Business-Website",
          duration: "2 Monate",
          techLabel: "techStack",
          techValue: "React.js, Node.js, Express.js, MongoDB",
          href: "https://meadowridgeftworth.com/",
          cta: "preview",
        },
      ],
    },
    testimonials: [
      {
        quote:
          "Not my first project with Imad. Fast, responsive, skilled, and great in communication. The entire process is always smooth and friendly, and once again I received a great website.",
        person: "Gyles Buckles",
        job: "CEO / Brussel Lake Paragon",
      },
      {
        quote:
          "Working with Imad has been an excellent experience. He consistently delivers high-quality work, stays responsive throughout the project, and ensures everything runs smoothly from start to finish. Highly recommended.",
        person: "Philip",
        job: "Travel Ink Media / D.O.P Director",
      },
    ],
    contact: {
      title: "Kontakt",
      phoneLabel: "telefon",
      phone: "+49 155 63801481",
      addressLabel: "adresse",
      address: "Thuringen, Deutschland",
      emailLabel: "e-mail",
      email: "imadahmad.ia0@gmail.com",
      followLabel: "folge mir",
    },
    clientsTitle: "Kunden",
    blog: {
      title: "Blog",
      commentsSuffix: "Kommentare",
      readMore: "Mehr lesen",
      posts: [
        {
          category: "design",
          title: "So veroffentlichst du Inhalte, die bei Google ranken",
          excerpt:
            "Eine praktische Checkliste fur bessere Struktur, hohe Lesbarkeit und Inhalte mit mehr organischer Sichtbarkeit.",
          date: "9 Apr 2022",
          comments: "17 Kommentare",
        },
        {
          category: "entwicklung",
          title: "Wie eine effiziente Seitenstruktur SEO verbessern kann",
          excerpt:
            "Schon kleine Architekturentscheidungen konnen Crawlbarkeit, Nutzerfuhrung und Performance deutlich verbessern.",
          date: "21 Feb 2022",
          comments: "34 Kommentare",
        },
        {
          category: "grundlagen",
          title: "Change Management fur nachhaltigen Kundenerfolg",
          excerpt:
            "Ein besserer Rollout hilft Kunden schneller, reduziert Reibung und schafft Vertrauen bei Produktanderungen.",
          date: "1 Jan 2022",
          comments: "10 Kommentare",
        },
      ],
      article: {
        backToHome: "Zuruck zur Startseite",
        pageTitle: "Mein Blog",
        tags: "wordpress, business",
        comments: "17 Kommentare",
        heading: "So veroffentlichst du Inhalte, die bei Google ranken",
        imageAlt: "Titelbild des Blogartikels",
        paragraphs: [
          "Starker Content beginnt mit einer klaren Suchintention. Definiere vor dem Schreiben genau, welche Frage die Seite beantworten soll, wem sie hilft und welche nachste Aktion du erreichen mochtest.",
          "Erstelle danach eine saubere Struktur mit aussagekraftigen Uberschriften, kurzen Absatzen und hilfreichen Beispielen. So verstehen Leser und Suchmaschinen das Thema schneller und die Seite bleibt leicht erfassbar.",
          "Nach der Veroffentlichung beginnt die Optimierung. Uberarbeite schwache Abschnitte, verbessere interne Verlinkungen und beobachte das Nutzerverhalten. Kontinuierliche Verbesserungen machen aus guten Artikeln oft sehr starke Ergebnisse.",
        ],
      },
    },
    footer: {
      copyrightName: "Imad Ahmad",
      madeWithLovePrefix: "Made with",
      madeWithLoveSuffix: "by Imad",
    },
  },
};
